# Site settings
title: "Đoàn Bình và Thầy Lang"
url-title: "Thuốc Nam"
description: "Đoàn Bình và Thuốc Nam"
paginate: 100
url: "http://mipateheo.com"
permalink: /:year/:month/:title/
future: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_words: 25

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
  deploy_style: compressed

gems: [jekyll-paginate]
